---
- name: Managed Server Configuration
  hosts: all
  tasks:
    - name: Install transmission
      ansible.builtin.apt:
        name:
          - transmission-cli
          - transmission-daemon
          - apparmor-utils
        state: present
        update_cache: yes
    - name: Fix apparmor
      ansible.builtin.shell: >-
        aa-complain /usr/bin/transmission-daemon
        && touch ~/.transmission-done
      args:
        creates: ~/.transmission-done
